### ISSUE TITLE
`smith start` fails

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#32]
```
ubuntu@ubuntu-xenial:/smith/font-test$ ls -a
.  ..
ubuntu@ubuntu-xenial:/smith/font-test$ smith start
Traceback (most recent call last):
  File "/usr/bin/smith", line 162, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/usr/lib/waf-1.6.8-37f3da91b02939d92d7b16576dd392ef/waflib/Scripting.py", line 47, in waf_entry_point
    ctx.execute()
  File "/usr/lib/waf-1.6.8-37f3da91b02939d92d7b16576dd392ef/waflib/extras/package.py", line 609, in execute
    shutil.copy(os.path.join(thisdir, 'OFL.txt'), 'OFL.txt')
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/lib/waf-1.6.8-37f3da91b02939d92d7b16576dd392ef/waflib/extras/OFL.txt'
ubuntu@ubuntu-xenial:/smith/font-test$ smith version
Version of smith currently installed (as a package):
Version: 0.3.2-0~2968-snapshot-201703232201~ubuntu16.04.1
Version of waf currently installed:
waf 1.6.8 (11517)
```

**Comment by n7s** [comment]
Oops, thought these templates files were there already. There are now added.
