### ISSUE TITLE
Error with new packaging structure (pyproject.toml)

### ISSUE THREAD

**Issue by n7s** [silnrsi/smith#80]
I only see this error with certain font projects in the new packaging structure (pyproject.toml): 

for example Padauk using the docker-jammy branch:

Waf: The wscript in '/smith/font-padauk' is unreadable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/waflib/Scripting.py", line 135, in waf_entry_point
    set_main_module(Context.run_dir + os.sep + wscript)
  File "/usr/local/lib/python3.10/dist-packages/waflib/Scripting.py", line 177, in set_main_module
    Context.g_module = Context.load_module(file_path)
  File "/usr/local/lib/python3.10/dist-packages/smithlib/wafplus.py", line 528, in load_module
    exec(compile(code, file_path, 'exec'), module.__dict__)
  File "/smith/font-padauk/wscript", line 78, in <module>
    font(target = process('khamti/'+f.target.replace('Padauk', 'NamKio'),
  File "/usr/local/lib/python3.10/dist-packages/smithlib/wsiwaf.py", line 52, in undeffer
    return c(*newa, **newkw)
  File "/usr/local/lib/python3.10/dist-packages/smithlib/font.py", line 25, in __init__
    kw['id'] = kw['test_suffix'] if 'test_suffix' in kw else kw['target'].lower().replace('.ttf','')
AttributeError: 'deferred_class' object has no attribute 'lower'
 
Packaging error, something else?

**Comment by n7s** [comment]
@tim-eves We need to test this new packaging approach with Noble's python 3.12 (see the pyproject.toml and related bits in the docker-jammy branch for now).

**Comment by n7s** [comment]
it turns out I'm to blame with some parts I forgot when shifting around of modules required by the need for a entry point in the new packaging approach. It is fixed in e01c045.
